openimsdk/openim-docker

- .env
- docker-compose.yaml
- example/.env
- example/basic-openim-server-dependency.yml
- openim-server/main/config/config.yaml
- openim-server/release-v3.2/config/config.yaml
> fix: add admin file

- .env
- docker-compose.yaml
- example/.env
- example/basic-openim-server-dependency.yml
- openim-server/main/config/config.yaml
- openim-server/release-v3.2/config/config.yaml
Reverts OpenIMSDK/openim-docker#4
> Revert "fix: add admin file"

- README.md
<br>
/kind documentation
/kind feature
build: build openim server v3.2 branch update README.md
```sh
git clone -b release-v1.2 https://github.com/openim-sigs/openim-docker openim/openim-docker && export openim=$(pwd)/openim && cd $openim/openim-docker && export CHAT_BRANCH="release-v1.2" && export SERVER_BRANCH="release-v3.2" &&  $openim/openim-docker/scripts/init-config.sh && docker-compose up -d
```
> build: build openim server v3.2 branch update README.md

- example/basic-openim-server-dependency.yml
> feat: update basic-openim-server-dependency.yml

- docker-compose.yaml
<br>
/kind bug
fix docker compose up failed because of mysql config lack platform arm
Fixes #
> fix: docker compose up failed because of mysql config lack platform arm

- .env.example
- .github/workflows/openimci.yml
- example/basic-openim-server-dependency.yml
- example/full-openim-server-and-chat.yml
- example/full-openim-server-chat-web-admin.yml
- example/full-openim-server-chat-web.yml
- example/only-openim-server.yml
- example/volume-all-server.yml
- scripts/mongo-init.sh
<br>
/kind feature
Could you please assist in addressing some lingering issues with the Mongo database in this PR? Additionally, it would be greatly appreciated if you could also tackle the CICD concerns. Thank you for your help!
Fixes #
> feat: add openim mongo logic

- openim-chat/README.md
- openim-server/README.md
<br>
/kind documentation
/kind feature
Could you please assist with testing this PR, which involves implementing the display of the openim-server and openim-chat directories
> feat: add go formity checker

- docker-compose.yaml
<br>
/kind documentation
/kind feature
> feat: add instance down rules yaml file

- docker-compose.yaml
Could you please consider adding support for various architectural systems to enable compatibility with a wide range of architectures? Thank you.
> Update docker-compose.yaml support arm/v6, arm/v8 

- .env.example
- FAQ-CN.md
- docker-compose.yaml
- example/basic-openim-server-dependency.yml
- example/full-openim-server-and-chat.yml
- example/full-openim-server-chat-web-admin.yml
- example/full-openim-server-chat-web.yml
- example/only-openim-server.yml
- example/volume-all-server.yml
<br>
Link: https://github.com/openimsdk/open-im-server/issues/1793
> feat: supoort openim-chat source code deployment in mac

- docker-compose.yaml
Update docker-compose.yaml fix mongo start
> Update docker-compose.yaml fix mongo start 

- .env
- docs/CODEOWNERS
> Update web/admin image 134

- .env
- docker-compose.yaml
> bump: update image to openIM v3.8.

- .github/workflows/openimci.yml
- config/alertmanager.yml
- config/email.tmpl
- config/instance-down-rules.yml
- config/prometheus.yml
- docker-compose.yaml
feat: update prometheus config.
> feat: update prometheus config.

- .env
bump(deps): update chat version to release.
> bump(deps): update chat version to release.

- docker-compose.yaml
reference openimsdk/open-im-server#2644
Fixes #
> fix: the attribute version is obsolete, remove it.

- docker-compose.yaml
Fixes #167
fix: Prometheus start
> fix: Prometheus start permission error

- .env
- config/prometheus.yml
- docker-compose.yaml
> Fix: prometheus config

- .env
> feat: update version

- .github/workflows/docker-Deployment-test.yml
> fix: cicd change secret

- .github/workflows/auto-invite-comment.yml
- .github/workflows/docker-Deployment-test.yml
- .github/workflows/help-comment-issue.yml
> build: update chat test.

- .env
> build: update openim server version to v3.8.3-patch.6
